# EDA

## quick and dirty clean
- `head data/outage.csv` reveals a mess

```
Major power outage events in the continental U.S.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Time period: January 2000 - July 2016,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Regions affected: Outages reported in this data file affected a single U.S. state at the time of occurrence,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
variables,OBS,YEAR,MONTH,U.S._STATE,POSTAL.CODE,NERC.REGION,CLIMATE.REGION,ANOMALY.LEVEL,CLIMATE.CATEGORY,OUTAGE.START.DATE,OUTAGE.START.TIME,OUTAGE.RESTORATION.DATE,OUTAGE.RESTORATION.TIME,CAUSE.CATEGORY,CAUSE.CATEGORY.DETAIL,HURRICANE.NAMES,OUTAGE.DURATION,DEMAND.LOSS.MW,CUSTOMERS.AFFECTED,RES.PRICE,COM.PRICE,IND.PRICE,TOTAL.PRICE,RES.SALES,COM.SALES,IND.SALES,TOTAL.SALES,RES.PERCEN,COM.PERCEN,IND.PERCEN,RES.CUSTOMERS,COM.CUSTOMERS,IND.CUSTOMERS,TOTAL.CUSTOMERS,RES.CUST.PCT,COM.CUST.PCT,IND.CUST.PCT,PC.REALGSP.STATE,PC.REALGSP.USA,PC.REALGSP.REL,PC.REALGSP.CHANGE,UTIL.REALGSP,TOTAL.REALGSP,UTIL.CONTRI,PI.UTIL.OFUSA,POPULATION,POPPCT_URBAN,POPPCT_UC,POPDEN_URBAN,POPDEN_UC,POPDEN_RURAL,AREAPCT_URBAN,AREAPCT_UC,PCT_LAND,PCT_WATER_TOT,PCT_WATER_INLAND
Units,,,,,,,,numeric,,"Day of the week, Month Day, Year",Hour:Minute:Second (AM / PM),"Day of the week, Month Day, Year",Hour:Minute:Second (AM / PM),,,,mins,Megawatt,,cents / kilowatt-hour,cents / kilowatt-hour,cents / kilowatt-hour,cents / kilowatt-hour,Megawatt-hour,Megawatt-hour,Megawatt-hour,Megawatt-hour,%,%,%,,,,,%,%,%,USD,USD,fraction,%,USD,USD,%,%,,%,%,persons per square mile,persons per square mile,persons per square mile,%,%,%,%,%
,1,2011,7,Minnesota,MN,MRO,East North Central,-0.3,normal,"Friday, July 1, 2011",5:00:00 PM,"Sunday, July 3, 2011",8:00:00 PM,severe weather,NA,NA,3060,NA,70000,11.6,9.18,6.81,9.28,2332915,2114774,2113291,6562520,35.5490726123501,32.2250294094342,32.2024313830663,2308736,276286,10673,2595696,88.9448,10.6440,0.4112,51268,47586,1.07737569873492,1.6,4802,274182,1.75139141154416,2.2,5348119,73.27,15.28,2279,1700.5,18.2,2.14,0.6,91.5926658691451,8.40733413085488,5.47874298334407
,2,2014,5,Minnesota,MN,MRO,East North Central,-0.1,normal,"Sunday, May 11, 2014",6:38:00 PM,"Sunday, May 11, 2014",6:39:00 PM,intentional attack,vandalism,NA,1,NA,NA,12.12,9.71,6.49,9.28,1586986,1807756,1887927,5284231,30.0324872247258,34.2103893641289,35.7275637647181,2345860,284978,9898,2640737,88.8335,10.7916,0.3748,53499,49091,1.08979242631032,1.9,5226,291955,1.79000188385196,2.2,5457125,73.27,15.28,2279,1700.5,18.2,2.14,0.6,91.5926658691451,8.40733413085488,5.47874298334407
,3,2010,10,Minnesota,MN,MRO,East North Central,-1.5,cold,"Tuesday, October 26, 2010",8:00:00 PM,"Thursday, October 28, 2010",10:00:00 PM,severe weather,heavy wind,NA,3000,NA,70000,10.87,8.19,6.07,8.15,1467293,1801683,1951295,5222116,28.0976715185951,34.5010145312743,37.365983444259,2300291,276463,10150,2586905,88.9206,10.6870,0.3924,50447,47287,1.0668259775414,2.7,4571,267895,1.70626551447395,2.1,5310903,73.27,15.28,2279,1700.5,18.2,2.14,0.6,91.5926658691451,8.40733413085488,5.47874298334407
```
- we can do a quick clean with the following commands:
  - `head -6 data/outage.csv | tail -1 | cut -d ',' -f 2- > data/outage_clean.csv` 
  - `tail -n +8 data/outage.csv | cut -d ',' -f 2- >> data/outage_clean.csv`
- let's double check the formatting `data/outage_.csv`

```
OBS,YEAR,MONTH,U.S._STATE,POSTAL.CODE,NERC.REGION,CLIMATE.REGION,ANOMALY.LEVEL,CLIMATE.CATEGORY,OUTAGE.START.DATE,OUTAGE.START.TIME,OUTAGE.RESTORATION.DATE,OUTAGE.RESTORATION.TIME,CAUSE.CATEGORY,CAUSE.CATEGORY.DETAIL,HURRICANE.NAMES,OUTAGE.DURATION,DEMAND.LOSS.MW,CUSTOMERS.AFFECTED,RES.PRICE,COM.PRICE,IND.PRICE,TOTAL.PRICE,RES.SALES,COM.SALES,IND.SALES,TOTAL.SALES,RES.PERCEN,COM.PERCEN,IND.PERCEN,RES.CUSTOMERS,COM.CUSTOMERS,IND.CUSTOMERS,TOTAL.CUSTOMERS,RES.CUST.PCT,COM.CUST.PCT,IND.CUST.PCT,PC.REALGSP.STATE,PC.REALGSP.USA,PC.REALGSP.REL,PC.REALGSP.CHANGE,UTIL.REALGSP,TOTAL.REALGSP,UTIL.CONTRI,PI.UTIL.OFUSA,POPULATION,POPPCT_URBAN,POPPCT_UC,POPDEN_URBAN,POPDEN_UC,POPDEN_RURAL,AREAPCT_URBAN,AREAPCT_UC,PCT_LAND,PCT_WATER_TOT,PCT_WATER_INLAND
1,2011,7,Minnesota,MN,MRO,East North Central,-0.3,normal,"Friday, July 1, 2011",5:00:00 PM,"Sunday, July 3, 2011",8:00:00 PM,severe weather,NA,NA,3060,NA,70000,11.6,9.18,6.81,9.28,2332915,2114774,2113291,6562520,35.5490726123501,32.2250294094342,32.2024313830663,2308736,276286,10673,2595696,88.9448,10.6440,0.4112,51268,47586,1.07737569873492,1.6,4802,274182,1.75139141154416,2.2,5348119,73.27,15.28,2279,1700.5,18.2,2.14,0.6,91.5926658691451,8.40733413085488,5.47874298334407
2,2014,5,Minnesota,MN,MRO,East North Central,-0.1,normal,"Sunday, May 11, 2014",6:38:00 PM,"Sunday, May 11, 2014",6:39:00 PM,intentional attack,vandalism,NA,1,NA,NA,12.12,9.71,6.49,9.28,1586986,1807756,1887927,5284231,30.0324872247258,34.2103893641289,35.7275637647181,2345860,284978,9898,2640737,88.8335,10.7916,0.3748,53499,49091,1.08979242631032,1.9,5226,291955,1.79000188385196,2.2,5457125,73.27,15.28,2279,1700.5,18.2,2.14,0.6,91.5926658691451,8.40733413085488,5.47874298334407
3,2010,10,Minnesota,MN,MRO,East North Central,-1.5,cold,"Tuesday, October 26, 2010",8:00:00 PM,"Thursday, October 28, 2010",10:00:00 PM,severe weather,heavy wind,NA,3000,NA,70000,10.87,8.19,6.07,8.15,1467293,1801683,1951295,5222116,28.0976715185951,34.5010145312743,37.365983444259,2300291,276463,10150,2586905,88.9206,10.6870,0.3924,50447,47287,1.0668259775414,2.7,4571,267895,1.70626551447395,2.1,5310903,73.27,15.28,2279,1700.5,18.2,2.14,0.6,91.5926658691451,8.40733413085488,5.47874298334407
4,2012,6,Minnesota,MN,MRO,East North Central,-0.1,normal,"Tuesday, June 19, 2012",4:30:00 AM,"Wednesday, June 20, 2012",11:00:00 PM,severe weather,thunderstorm,NA,2550,NA,68200,11.79,9.25,6.71,9.19,1851519,1941174,1993026,5787064,31.9940992530928,33.5433304349148,34.4393288202792,2317336,278466,11010,2606813,88.8954,10.6822,0.4224,51598,48156,1.07147603621563,0.6,5364,277627,1.93208873776686,2.2,5380443,73.27,15.28,2279,1700.5,18.2,2.14,0.6,91.5926658691451,8.40733413085488,5.47874298334407
5,2015,7,Minnesota,MN,MRO,East North Central,1.2,warm,"Saturday, July 18, 2015",2:00:00 AM,"Sunday, July 19, 2015",7:00:00 AM,severe weather,NA,NA,1740,250,250000,13.07,10.16,7.74,10.43,2028875,2161612,1777937,5970339,33.982576198772,36.2058502875632,29.7794982830958,2374674,289044,9812,2673531,88.8216,10.8113,0.3670,54431,49844,1.09202712462884,1.7,4873,292023,1.66870417741068,2.2,5489594,73.27,15.28,2279,1700.5,18.2,2.14,0.6,91.5926658691451,8.40733413085488,5.47874298334407
6,2010,11,Minnesota,MN,MRO,East North Central,-1.4,cold,"Saturday, November 13, 2010",3:00:00 PM,"Sunday, November 14, 2010",10:00:00 PM,severe weather,winter storm,NA,1860,NA,60000,10.63,8.34,6.15,8.28,1676347,1786144,1909874,5374150,31.1927839751403,33.2358419470986,35.5381595229013,2300291,276463,10150,2586905,88.9206,10.6870,0.3924,50447,47287,1.0668259775414,2.7,4571,267895,1.70626551447395,2.1,5310903,73.27,15.28,2279,1700.5,18.2,2.14,0.6,91.5926658691451,8.40733413085488,5.47874298334407
7,2010,7,Minnesota,MN,MRO,East North Central,-0.9,cold,"Saturday, July 17, 2010",8:30:00 PM,"Monday, July 19, 2010",10:00:00 PM,severe weather,tornadoes,NA,2970,NA,63000,11.41,9.11,6.71,9.12,2187537,2100828,2084709,6374935,34.3146557572744,32.9545007125563,32.701651075658,2300291,276463,10150,2586905,88.9206,10.6870,0.3924,50447,47287,1.0668259775414,2.7,4571,267895,1.70626551447395,2.1,5310903,73.27,15.28,2279,1700.5,18.2,2.14,0.6,91.5926658691451,8.40733413085488,5.47874298334407
8,2005,6,Minnesota,MN,MRO,East North Central,0.2,normal,"Wednesday, June 8, 2005",4:00:00 AM,"Friday, June 10, 2005",10:00:00 PM,severe weather,thunderstorm,NA,3960,75,3.00E+05,9.1,7.22,5.69,7.36,1883344,1935444,1786652,5607498,33.5861733700128,34.5152864967584,31.861839273059,2211000,255645,8266,2474912,89.3365,10.3295,0.3340,52445,48090,1.09055936785194,2,3997,268496,1.48866277337465,2.1,5119598,73.27,15.28,2279,1700.5,18.2,2.14,0.6,91.5926658691451,8.40733413085488,5.47874298334407
9,2015,3,Minnesota,MN,MRO,East North Central,0.6,warm,"Monday, March 16, 2015",7:31:00 AM,"Monday, March 16, 2015",10:06:00 AM,intentional attack,sabotage,NA,155,20,5941,11.53,8.89,6.61,9.03,1844298,1956866,1795865,5599486,32.9369159955039,34.9472433719809,32.0719616050473,2374674,289044,9812,2673531,88.8216,10.8113,0.3670,54431,49844,1.09202712462884,1.7,4873,292023,1.66870417741068,2.2,5489594,73.27,15.28,2279,1700.5,18.2,2.14,0.6,91.5926658691451,8.40733413085488,5.47874298334407
```
- much better now we can dig in with `pandas`!

## initial inspection

### import libraries

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import statsmodels.api as sm
from statsmodels.formula.api import ols

### Read `outage_clean.csv`

In [7]:
data = "../data/outage_clean.csv"
df = pd.read_csv(data)
# Output dataset info, summary statistics, and null counts
print("Dataset Info:")
df.info()

print("\nMissing Values per Column:")
print(df.isna().sum()[df.isna().sum() > 0])

print("\nSummary Statistics for Numeric Columns:")
display(df.describe())


# --- 1. PRELIMINARY CLEANING ---

# A. Drop the unnecessary index column
if 'OBS' in df.columns:
    df = df.drop(columns=['OBS'])

# B. Consolidate Temporal Features into Datetime objects
df['OUTAGE.START'] = pd.to_datetime(df['OUTAGE.START.DATE'] + ' ' + df['OUTAGE.START.TIME'], errors='coerce')
df['OUTAGE.RESTORATION'] = pd.to_datetime(df['OUTAGE.RESTORATION.DATE'] + ' ' + df['OUTAGE.RESTORATION.TIME'], errors='coerce')

# Drop the redundant temporal columns
temporal_cols_to_drop = [
    'YEAR', 'MONTH', 
    'OUTAGE.START.DATE', 'OUTAGE.START.TIME', 
    'OUTAGE.RESTORATION.DATE', 'OUTAGE.RESTORATION.TIME'
]
df = df.drop(columns=[col for col in temporal_cols_to_drop if col in df.columns])

# C. Convert HURRICANE.NAMES to a boolean flag and drop the original
df['IS_HURRICANE'] = df['HURRICANE.NAMES'].notna()
df = df.drop(columns=['HURRICANE.NAMES'])

# D. Standardize categorical text (lowercase and strip whitespace)
string_cols = df.select_dtypes(include=['object']).columns
for col in string_cols:
    df[col] = df[col].str.lower().str.strip()


# --- 2. INSPECTING MISSING OUTAGE DURATIONS ---

# Isolate the rows where OUTAGE.DURATION is missing
df_missing_duration = df[df['OUTAGE.DURATION'].isna()]

print(f"Total rows missing OUTAGE.DURATION: {len(df_missing_duration)}")

# Check if these missing durations are clustered around specific causes
print("\nMissing Durations by Cause Category:")
display(df_missing_duration['CAUSE.CATEGORY'].value_counts(dropna=False))

# Check if they are clustered around specific years
print("\nMissing Durations by Start Year:")
display(df_missing_duration['OUTAGE.START'].dt.year.value_counts(dropna=False))

# Check if restoration times are also missing for these rows (indicating ongoing outages)
missing_restoration = df_missing_duration['OUTAGE.RESTORATION'].isna().sum()
print(f"\nOut of {len(df_missing_duration)} missing durations, {missing_restoration} are also missing RESTORATION times.")

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1534 entries, 0 to 1533
Data columns (total 56 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   OBS                      1534 non-null   int64
 1   YEAR                     1534 non-null   int64
 2   MONTH                    1525 non-null   float64
 3   U.S._STATE               1534 non-null   object
 4   POSTAL.CODE              1534 non-null   object
 5   NERC.REGION              1534 non-null   object
 6   CLIMATE.REGION           1528 non-null   object
 7   ANOMALY.LEVEL            1525 non-null   float64
 8   CLIMATE.CATEGORY         1525 non-null   object
 9   OUTAGE.START.DATE        1525 non-null   object
 10  OUTAGE.START.TIME        1525 non-null   object
 11  OUTAGE.RESTORATION.DATE  1476 non-null   object
 12  OUTAGE.RESTORATION.TIME  1476 non-null   object
 13  CAUSE.CATEGORY           1534 non-null   object
 14  CAUSE.CATEGORY.DETAIL    1063 non-null   object
 15  HURRICANE.NAMES          72 non-null     object
 16  OUTAGE.DURATION          1476 non-null   float64
 17  DEMAND.LOSS.MW           829 non-null    float64
 18  CUSTOMERS.AFFECTED       1091 non-null   float64
 19  RES.PRICE                1512 non-null   float64
 20  COM.PRICE                1512 non-null   float64
 21  IND.PRICE                1512 non-null   float64
 22  TOTAL.PRICE              1512 non-null   float64
 23  RES.SALES                1512 non-null   float64
 24  COM.SALES                1512 non-null   float64
 25  IND.SALES                1512 non-null   float64
 26  TOTAL.SALES              1512 non-null   float64
 27  RES.PERCEN               1512 non-null   float64
 28  COM.PERCEN               1512 non-null   float64
 29  IND.PERCEN               1512 non-null   float64
 30  RES.CUSTOMERS            1534 non-null   int64
 31  COM.CUSTOMERS            1534 non-null   int64
 32  IND.CUSTOMERS            1534 non-null   int64
 33  TOTAL.CUSTOMERS          1534 non-null   int64
 34  RES.CUST.PCT             1534 non-null   float64
 35  COM.CUST.PCT             1534 non-null   float64
 36  IND.CUST.PCT             1534 non-null   float64
 37  PC.REALGSP.STATE         1534 non-null   int64
 38  PC.REALGSP.USA           1534 non-null   int64
 39  PC.REALGSP.REL           1534 non-null   float64
 40  PC.REALGSP.CHANGE        1534 non-null   float64
 41  UTIL.REALGSP             1534 non-null   int64
 42  TOTAL.REALGSP            1534 non-null   int64
 43  UTIL.CONTRI              1534 non-null   float64
 44  PI.UTIL.OFUSA            1534 non-null   float64
 45  POPULATION               1534 non-null   int64
 46  POPPCT_URBAN             1534 non-null   float64
 47  POPPCT_UC                1534 non-null   float64
 48  POPDEN_URBAN             1534 non-null   float64
 49  POPDEN_UC                1524 non-null   float64
 50  POPDEN_RURAL             1524 non-null   float64
 51  AREAPCT_URBAN            1534 non-null   float64
 52  AREAPCT_UC               1534 non-null   float64
 53  PCT_LAND                 1534 non-null   float64
 54  PCT_WATER_TOT            1534 non-null   float64
 55  PCT_WATER_INLAND         1534 non-null   float64
dtypes: float64(33), int64(11), object(12)
memory usage: 671.3+ KB

Missing Values per Column:
MONTH                         9
CLIMATE.REGION                6
ANOMALY.LEVEL                 9
CLIMATE.CATEGORY              9
OUTAGE.START.DATE             9
OUTAGE.START.TIME             9
OUTAGE.RESTORATION.DATE      58
OUTAGE.RESTORATION.TIME      58
CAUSE.CATEGORY.DETAIL       471
HURRICANE.NAMES            1462
OUTAGE.DURATION              58
DEMAND.LOSS.MW              705
CUSTOMERS.AFFECTED          443
RES.PRICE                    22
COM.PRICE                    22
IND.PRICE                    22
TOTAL.PRICE                  22
RES.SALES                    22
COM.SALES                    22
IND.SALES                    22
TOTAL.SALES                  22
RES.PERCEN                   22
COM.PERCEN                   22
IND.PERCEN                   22
POPDEN_UC                    10
POPDEN_RURAL                 10
dtype: int64

Summary Statistics for Numeric Columns:

,OBS,YEAR,MONTH,ANOMALY.LEVEL,OUTAGE.DURATION,DEMAND.LOSS.MW,CUSTOMERS.AFFECTED,RES.PRICE,COM.PRICE,IND.PRICE,...,POPPCT_URBAN,POPPCT_UC,POPDEN_URBAN,POPDEN_UC,POPDEN_RURAL,AREAPCT_URBAN,AREAPCT_UC,PCT_LAND,PCT_WATER_TOT,PCT_WATER_INLAND
count,1534.000000,1534.000000,1525.000000,1525.000000,1476.000000,829.000000,1.091000e+03,1512.000000,1512.000000,1512.000000,...,1534.000000,1534.000000,1534.000000,1524.000000,1524.000000,1534.000000,1534.000000,1534.000000,1534.000000,1534.000000
mean,767.500000,2010.119296,6.234754,-0.096852,2625.398374,536.287093,1.434562e+05,11.968373,10.135053,7.341468,...,80.967112,9.545267,2594.174967,1558.041142,39.473491,8.604348,1.117608,90.158521,9.841405,2.911191
std,442.971971,3.822306,3.254510,0.739957,5942.483307,2196.450393,2.869863e+05,3.088631,2.824150,2.473902,...,11.900026,5.240315,1083.200091,313.149226,30.890074,11.134773,0.995424,10.519099,10.518892,2.115077
min,1.000000,2000.000000,1.000000,-1.600000,0.000000,0.000000,0.000000e+00,5.650000,4.700000,3.200000,...,38.660000,0.000000,1232.600000,988.700000,0.400000,0.050000,0.000000,58.459995,0.240151,0.240151
25%,384.250000,2008.000000,4.000000,-0.500000,102.250000,3.000000,9.650000e+03,9.540000,8.017500,5.697500,...,74.570000,5.220000,2016.300000,1307.800000,15.200000,3.350000,0.590000,86.382550,2.742036,1.730658
50%,767.500000,2011.000000,6.000000,-0.300000,701.000000,168.000000,7.013500e+04,11.460000,9.465000,6.710000,...,84.050000,9.080000,2380.000000,1528.600000,29.500000,5.280000,0.970000,95.164177,4.835823,2.090873
75%,1150.750000,2013.000000,9.000000,0.300000,2880.000000,400.000000,1.500000e+05,13.900000,11.340000,8.590000,...,89.810000,12.020000,2847.425000,1732.200000,54.600000,8.680000,1.460000,97.258336,13.617450,3.645862
max,1534.000000,2016.000000,12.000000,2.300000,108653.000000,41788.000000,3.241437e+06,34.580000,32.140000,27.850000,...,100.000000,40.250000,9856.500000,2220.700000,142.300000,100.000000,6.210000,99.759849,41.540005,10.294118

/tmp/ipykernel_60017/2721146974.py:21: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['OUTAGE.START'] = pd.to_datetime(df['OUTAGE.START.DATE'] + ' ' + df['OUTAGE.START.TIME'], errors='coerce')
/tmp/ipykernel_60017/2721146974.py:22: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['OUTAGE.RESTORATION'] = pd.to_datetime(df['OUTAGE.RESTORATION.DATE'] + ' ' + df['OUTAGE.RESTORATION.TIME'], errors='coerce')

Total rows missing OUTAGE.DURATION: 58

Missing Durations by Cause Category:

CAUSE.CATEGORY
severe weather                   19
intentional attack               15
fuel supply emergency            13
equipment failure                 5
system operability disruption     4
islanding                         2
Name: count, dtype: int64

Missing Durations by Start Year:

OUTAGE.START
2015.0    13
2016.0    12
NaN        9
2014.0     8
2000.0     6
2007.0     2
2002.0     2
2008.0     1
2013.0     1
2001.0     1
2009.0     1
2012.0     1
2005.0     1
Name: count, dtype: int64

Out of 58 missing durations, 58 are also missing RESTORATION times.

In [6]:
column_categories = {
    "identifier": [
        "OBS"
    ],
    "temporal": [
        "YEAR", "MONTH", 
        "OUTAGE.START.DATE", "OUTAGE.START.TIME", 
        "OUTAGE.RESTORATION.DATE", "OUTAGE.RESTORATION.TIME", 
        "OUTAGE.DURATION"
    ],
    "spatial_and_climate": [
        "U.S._STATE", "POSTAL.CODE", "NERC.REGION", 
        "CLIMATE.REGION", "CLIMATE.CATEGORY", "ANOMALY.LEVEL"
    ],
    "outage_impact_and_cause": [
        "CAUSE.CATEGORY", "CAUSE.CATEGORY.DETAIL", "HURRICANE.NAMES", 
        "DEMAND.LOSS.MW", "CUSTOMERS.AFFECTED"
    ],
    "electricity_economics": [
        "RES.PRICE", "COM.PRICE", "IND.PRICE", "TOTAL.PRICE", 
        "RES.SALES", "COM.SALES", "IND.SALES", "TOTAL.SALES", 
        "RES.PERCEN", "COM.PERCEN", "IND.PERCEN", 
        "RES.CUSTOMERS", "COM.CUSTOMERS", "IND.CUSTOMERS", "TOTAL.CUSTOMERS", 
        "RES.CUST.PCT", "COM.CUST.PCT", "IND.CUST.PCT"
    ],
    "state_economics": [
        "PC.REALGSP.STATE", "PC.REALGSP.USA", "PC.REALGSP.REL", 
        "PC.REALGSP.CHANGE", "UTIL.REALGSP", "TOTAL.REALGSP", 
        "UTIL.CONTRI", "PI.UTIL.OFUSA"
    ],
    "demographics_and_land_use": [
        "POPULATION", "POPPCT_URBAN", "POPPCT_UC", 
        "POPDEN_URBAN", "POPDEN_UC", "POPDEN_RURAL", 
        "AREAPCT_URBAN", "AREAPCT_UC", 
        "PCT_LAND", "PCT_WATER_TOT", "PCT_WATER_INLAND"
    ]
}

col_i = 0
for category in column_categories.keys():
    col_i += len(column_categories[category])
    print(70*'=')
    print(f"{category}: {len(column_categories[category])} columns")
    print(70*'=')
    print(df[column_categories[category]].head())
    print(70*'_')
    print("\n\n")
print(f"Total columns: {col_i}")
# Example of how to use this to quickly subset the dataframe:
#df_economics = df[column_categories['state_economics']]
#print(df_economics.head())

======================================================================
identifier: 1 columns
======================================================================
   OBS
0    1
1    2
2    3
3    4
4    5
______________________________________________________________________



======================================================================
temporal: 7 columns
======================================================================
   YEAR  MONTH          OUTAGE.START.DATE OUTAGE.START.TIME  \
0  2011    7.0       Friday, July 1, 2011        5:00:00 PM
1  2014    5.0       Sunday, May 11, 2014        6:38:00 PM
2  2010   10.0  Tuesday, October 26, 2010        8:00:00 PM
3  2012    6.0     Tuesday, June 19, 2012        4:30:00 AM
4  2015    7.0    Saturday, July 18, 2015        2:00:00 AM

      OUTAGE.RESTORATION.DATE OUTAGE.RESTORATION.TIME  OUTAGE.DURATION
0        Sunday, July 3, 2011              8:00:00 PM           3060.0
1        Sunday, May 11, 2014              6:39:00 PM              1.0
2  Thursday, October 28, 2010             10:00:00 PM           3000.0
3    Wednesday, June 20, 2012             11:00:00 PM           2550.0
4       Sunday, July 19, 2015              7:00:00 AM           1740.0
______________________________________________________________________



======================================================================
spatial_and_climate: 6 columns
======================================================================
  U.S._STATE POSTAL.CODE NERC.REGION      CLIMATE.REGION CLIMATE.CATEGORY  \
0  Minnesota          MN         MRO  East North Central           normal
1  Minnesota          MN         MRO  East North Central           normal
2  Minnesota          MN         MRO  East North Central             cold
3  Minnesota          MN         MRO  East North Central           normal
4  Minnesota          MN         MRO  East North Central             warm

   ANOMALY.LEVEL
0           -0.3
1           -0.1
2           -1.5
3           -0.1
4            1.2
______________________________________________________________________



======================================================================
outage_impact_and_cause: 5 columns
======================================================================
       CAUSE.CATEGORY CAUSE.CATEGORY.DETAIL HURRICANE.NAMES  DEMAND.LOSS.MW  \
0      severe weather                   NaN             NaN             NaN
1  intentional attack             vandalism             NaN             NaN
2      severe weather            heavy wind             NaN             NaN
3      severe weather          thunderstorm             NaN             NaN
4      severe weather                   NaN             NaN           250.0

   CUSTOMERS.AFFECTED
0             70000.0
1                 NaN
2             70000.0
3             68200.0
4            250000.0
______________________________________________________________________



======================================================================
electricity_economics: 18 columns
======================================================================
   RES.PRICE  COM.PRICE  IND.PRICE  TOTAL.PRICE  RES.SALES  COM.SALES  \
0      11.60       9.18       6.81         9.28  2332915.0  2114774.0
1      12.12       9.71       6.49         9.28  1586986.0  1807756.0
2      10.87       8.19       6.07         8.15  1467293.0  1801683.0
3      11.79       9.25       6.71         9.19  1851519.0  1941174.0
4      13.07      10.16       7.74        10.43  2028875.0  2161612.0

   IND.SALES  TOTAL.SALES  RES.PERCEN  COM.PERCEN  IND.PERCEN  RES.CUSTOMERS  \
0  2113291.0    6562520.0   35.549073   32.225029   32.202431        2308736
1  1887927.0    5284231.0   30.032487   34.210389   35.727564        2345860
2  1951295.0    5222116.0   28.097672   34.501015   37.365983        2300291
3  1993026.0    5787064.0   31.994099   33.543330   34.439329        2317336
4  1777937.0    5970339.0   33.982576   36.205850   29.779498        2374674

   COM.CUSTOMERS  IND.CUSTOMERS  TOTAL.CUSTOMERS  RES.CUST.PCT  COM.CUST.PCT  \
0         276286          10673          2595696       88.9448       10.6440
1         284978           9898          2640737       88.8335       10.7916
2         276463          10150          2586905       88.9206       10.6870
3         278466          11010          2606813       88.8954       10.6822
4         289044           9812          2673531       88.8216       10.8113

   IND.CUST.PCT
0        0.4112
1        0.3748
2        0.3924
3        0.4224
4        0.3670
______________________________________________________________________



======================================================================
state_economics: 8 columns
======================================================================
   PC.REALGSP.STATE  PC.REALGSP.USA  PC.REALGSP.REL  PC.REALGSP.CHANGE  \
0             51268           47586        1.077376                1.6
1             53499           49091        1.089792                1.9
2             50447           47287        1.066826                2.7
3             51598           48156        1.071476                0.6
4             54431           49844        1.092027                1.7

   UTIL.REALGSP  TOTAL.REALGSP  UTIL.CONTRI  PI.UTIL.OFUSA
0          4802         274182     1.751391            2.2
1          5226         291955     1.790002            2.2
2          4571         267895     1.706266            2.1
3          5364         277627     1.932089            2.2
4          4873         292023     1.668704            2.2
______________________________________________________________________



======================================================================
demographics_and_land_use: 11 columns
======================================================================
   POPULATION  POPPCT_URBAN  POPPCT_UC  POPDEN_URBAN  POPDEN_UC  POPDEN_RURAL  \
0     5348119         73.27      15.28        2279.0     1700.5          18.2
1     5457125         73.27      15.28        2279.0     1700.5          18.2
2     5310903         73.27      15.28        2279.0     1700.5          18.2
3     5380443         73.27      15.28        2279.0     1700.5          18.2
4     5489594         73.27      15.28        2279.0     1700.5          18.2

   AREAPCT_URBAN  AREAPCT_UC   PCT_LAND  PCT_WATER_TOT  PCT_WATER_INLAND
0           2.14         0.6  91.592666       8.407334          5.478743
1           2.14         0.6  91.592666       8.407334          5.478743
2           2.14         0.6  91.592666       8.407334          5.478743
3           2.14         0.6  91.592666       8.407334          5.478743
4           2.14         0.6  91.592666       8.407334          5.478743
______________________________________________________________________



Total columns: 56

## Check Number of Columns and Rows

In [4]:
label_w = 30
num_w = 8
print(f"{'columns in outage data:':>{label_w}} {df.shape[1]:>{num_w}}")
print(f"{'rows in outage data:':>{label_w}} {df.shape[0]:>{num_w}}")
print(f"{'total elements in outage data:':>{label_w}} {df.size:>{num_w}}")

       columns in outage data:       56
          rows in outage data:     1534
total elements in outage data:    85904

## Check NaN and dtype

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1534 entries, 0 to 1533
Data columns (total 56 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   OBS                      1534 non-null   int64
 1   YEAR                     1534 non-null   int64
 2   MONTH                    1525 non-null   float64
 3   U.S._STATE               1534 non-null   object
 4   POSTAL.CODE              1534 non-null   object
 5   NERC.REGION              1534 non-null   object
 6   CLIMATE.REGION           1528 non-null   object
 7   ANOMALY.LEVEL            1525 non-null   float64
 8   CLIMATE.CATEGORY         1525 non-null   object
 9   OUTAGE.START.DATE        1525 non-null   object
 10  OUTAGE.START.TIME        1525 non-null   object
 11  OUTAGE.RESTORATION.DATE  1476 non-null   object
 12  OUTAGE.RESTORATION.TIME  1476 non-null   object
 13  CAUSE.CATEGORY           1534 non-null   object
 14  CAUSE.CATEGORY.DETAIL    1063 non-null   object
 15  HURRICANE.NAMES          72 non-null     object
 16  OUTAGE.DURATION          1476 non-null   float64
 17  DEMAND.LOSS.MW           829 non-null    float64
 18  CUSTOMERS.AFFECTED       1091 non-null   float64
 19  RES.PRICE                1512 non-null   float64
 20  COM.PRICE                1512 non-null   float64
 21  IND.PRICE                1512 non-null   float64
 22  TOTAL.PRICE              1512 non-null   float64
 23  RES.SALES                1512 non-null   float64
 24  COM.SALES                1512 non-null   float64
 25  IND.SALES                1512 non-null   float64
 26  TOTAL.SALES              1512 non-null   float64
 27  RES.PERCEN               1512 non-null   float64
 28  COM.PERCEN               1512 non-null   float64
 29  IND.PERCEN               1512 non-null   float64
 30  RES.CUSTOMERS            1534 non-null   int64
 31  COM.CUSTOMERS            1534 non-null   int64
 32  IND.CUSTOMERS            1534 non-null   int64
 33  TOTAL.CUSTOMERS          1534 non-null   int64
 34  RES.CUST.PCT             1534 non-null   float64
 35  COM.CUST.PCT             1534 non-null   float64
 36  IND.CUST.PCT             1534 non-null   float64
 37  PC.REALGSP.STATE         1534 non-null   int64
 38  PC.REALGSP.USA           1534 non-null   int64
 39  PC.REALGSP.REL           1534 non-null   float64
 40  PC.REALGSP.CHANGE        1534 non-null   float64
 41  UTIL.REALGSP             1534 non-null   int64
 42  TOTAL.REALGSP            1534 non-null   int64
 43  UTIL.CONTRI              1534 non-null   float64
 44  PI.UTIL.OFUSA            1534 non-null   float64
 45  POPULATION               1534 non-null   int64
 46  POPPCT_URBAN             1534 non-null   float64
 47  POPPCT_UC                1534 non-null   float64
 48  POPDEN_URBAN             1534 non-null   float64
 49  POPDEN_UC                1524 non-null   float64
 50  POPDEN_RURAL             1524 non-null   float64
 51  AREAPCT_URBAN            1534 non-null   float64
 52  AREAPCT_UC               1534 non-null   float64
 53  PCT_LAND                 1534 non-null   float64
 54  PCT_WATER_TOT            1534 non-null   float64
 55  PCT_WATER_INLAND         1534 non-null   float64
dtypes: float64(33), int64(11), object(12)
memory usage: 671.3+ KB

## unvariate v2
*Comment: The histogram of outage durations is severely right-skewed, demonstrating that while the vast majority of grid failures are resolved relatively quickly, a small number of catastrophic events take an exceptionally long time to repair. Similarly, the distribution for affected customers shows a massive concentration near the lower end with extreme upper outliers, indicating that millions of users are only impacted during rare, severe systemic failures.

In [8]:
# 1. Distribution of Outage Duration
# Dropping NaNs strictly for the visualization to avoid Plotly errors
df_duration = df.dropna(subset=['OUTAGE.DURATION'])
fig_uni_1 = px.histogram(df_duration, x='OUTAGE.DURATION', 
                         title='Distribution of Outage Durations (mins)',
                         marginal='box', nbins=50, color_discrete_sequence=['#1f77b4'])
fig_uni_1.show()

# 2. Distribution of Customers Affected
df_customers = df.dropna(subset=['CUSTOMERS.AFFECTED'])
fig_uni_2 = px.histogram(df_customers, x='CUSTOMERS.AFFECTED', 
                         title='Distribution of Customers Affected',
                         marginal='box', nbins=50, color_discrete_sequence=['#ff7f0e'])
fig_uni_2.show()

## bivariate v2
*Comment: The histogram of outage durations is severely right-skewed, demonstrating that while the vast majority of grid failures are resolved relatively quickly, a small number of catastrophic events take an exceptionally long time to repair. Similarly, the distribution for affected customers shows a massive concentration near the lower end with extreme upper outliers, indicating that millions of users are only impacted during rare, severe systemic failures.

In [13]:
# 1. Outage Duration vs. Demand Loss Scatter Plot
df_scatter = df.dropna(subset=['OUTAGE.DURATION', 'DEMAND.LOSS.MW'])
fig_bi_1 = px.scatter(df_scatter, x='DEMAND.LOSS.MW', y='OUTAGE.DURATION',
                      title='Outage Duration vs. Megawatt Demand Loss',
                      opacity=0.5, trendline='ols', color='CAUSE.CATEGORY')
fig_bi_1.show()

# 2. Outage Duration by Climate Region Box Plot (Adjusted for 0s)
df_box = df.dropna(subset=['OUTAGE.DURATION', 'CLIMATE.REGION']).copy()

# Add 1 to duration to prevent log(0) errors and allow 0s to appear at the bottom
df_box['OUTAGE.DURATION.ADJUSTED'] = df_box['OUTAGE.DURATION'] + 1

fig_bi_2 = px.box(df_box, x='CLIMATE.REGION', y='OUTAGE.DURATION.ADJUSTED',
                  title='Outage Duration Across Climate Regions',
                  color='CLIMATE.REGION')

# Update y-axis to log scale and adjust the label to reflect the mathematical change
fig_bi_2.update_layout(
    yaxis_type="log",
    yaxis_title="OUTAGE.DURATION (mins + 1)"
)
fig_bi_2.show()

## Interesting Aggregates
* Comments: This aggregate table provides a critical macro-level view by ranking root causes by their average severity. It clearly isolates which broad event categories—such as extreme weather versus physical attacks—inflict the deepest sustained damage to the grid and impact the largest customer bases.

In [10]:
# Pivot table for average duration and demand loss by Cause Category
agg_table = df.pivot_table(
    values=['OUTAGE.DURATION', 'DEMAND.LOSS.MW', 'CUSTOMERS.AFFECTED'], 
    index='CAUSE.CATEGORY', 
    aggfunc='mean'
).dropna().sort_values(by='OUTAGE.DURATION', ascending=False)

# Formatting for better readability
agg_table = agg_table.round(2)
display(agg_table)

,CUSTOMERS.AFFECTED,DEMAND.LOSS.MW,OUTAGE.DURATION
CAUSE.CATEGORY,,,
fuel supply emergency,0.14,540.22,13484.03
severe weather,188574.80,618.66,3883.99
equipment failure,101935.57,372.40,1816.91
public appeal,7618.76,1784.93,1468.45
system operability disruption,211066.02,928.90,728.87
intentional attack,1790.53,9.15,429.98
islanding,6169.09,396.56,200.55

### Check date time columns

In [6]:
# check datetime columns
date_time = [i for i in df.columns if 'TIME' in i] +[i for i in df.columns if 'DATE' in i]
df[date_time].head()

,OUTAGE.START.TIME,OUTAGE.RESTORATION.TIME,OUTAGE.START.DATE,OUTAGE.RESTORATION.DATE
0,5:00:00 PM,8:00:00 PM,"Friday, July 1, 2011","Sunday, July 3, 2011"
1,6:38:00 PM,6:39:00 PM,"Sunday, May 11, 2014","Sunday, May 11, 2014"
2,8:00:00 PM,10:00:00 PM,"Tuesday, October 26, 2010","Thursday, October 28, 2010"
3,4:30:00 AM,11:00:00 PM,"Tuesday, June 19, 2012","Wednesday, June 20, 2012"
4,2:00:00 AM,7:00:00 AM,"Saturday, July 18, 2015","Sunday, July 19, 2015"

In [7]:
# Combine the columns with a space separating date and time
start_combined = df['OUTAGE.START.DATE'] + ' ' + df['OUTAGE.START.TIME']
restoration_combined = df['OUTAGE.RESTORATION.DATE'] + ' ' + df['OUTAGE.RESTORATION.TIME']

# Define the explicit format string matching your dataframe's text
# %A: Full Weekday, %B: Full Month, %d: Day, %Y: 4-digit Year
# %I: Hour (12hr), %M: Minute, %S: Second, %p: AM/PM
date_format = "%A, %B %d, %Y %I:%M:%S %p"

# Apply to_datetime with the explicitly specified format
df['START.DATETIME'] = pd.to_datetime(start_combined, format=date_format, errors='coerce')
df['RESTORATION.DATETIME'] = pd.to_datetime(restoration_combined, format=date_format, errors='coerce')
# 3. Check the results
print(df[['START.DATETIME', 'RESTORATION.DATETIME']].info())
print(df[['START.DATETIME', 'RESTORATION.DATETIME']].head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1534 entries, 0 to 1533
Data columns (total 2 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   START.DATETIME        1525 non-null   datetime64[ns]
 1   RESTORATION.DATETIME  1476 non-null   datetime64[ns]
dtypes: datetime64[ns](2)
memory usage: 24.1 KB
None
       START.DATETIME RESTORATION.DATETIME
0 2011-07-01 17:00:00  2011-07-03 20:00:00
1 2014-05-11 18:38:00  2014-05-11 18:39:00
2 2010-10-26 20:00:00  2010-10-28 22:00:00
3 2012-06-19 04:30:00  2012-06-20 23:00:00
4 2015-07-18 02:00:00  2015-07-19 07:00:00

In [8]:
# 2. Drop the redundant string columns to clean up the dataframe
cols_to_drop = ['OUTAGE.START.DATE', 'OUTAGE.START.TIME', 
                'OUTAGE.RESTORATION.DATE', 'OUTAGE.RESTORATION.TIME']
df_cleaned = df.drop(columns=cols_to_drop)

# 3. Filter out rows where crucial datetime info is missing for our analysis
df_cleaned = df_cleaned.dropna(subset=['START.DATETIME', 'RESTORATION.DATETIME', 'OUTAGE.DURATION'])

# Show the head of the cleaned DataFrame (Assignment Requirement)
display(df_cleaned.head())

,OBS,YEAR,MONTH,U.S._STATE,POSTAL.CODE,NERC.REGION,CLIMATE.REGION,ANOMALY.LEVEL,CLIMATE.CATEGORY,CAUSE.CATEGORY,...,POPDEN_URBAN,POPDEN_UC,POPDEN_RURAL,AREAPCT_URBAN,AREAPCT_UC,PCT_LAND,PCT_WATER_TOT,PCT_WATER_INLAND,START.DATETIME,RESTORATION.DATETIME
0,1,2011,7.0,Minnesota,MN,MRO,East North Central,-0.3,normal,severe weather,...,2279.0,1700.5,18.2,2.14,0.6,91.592666,8.407334,5.478743,2011-07-01 17:00:00,2011-07-03 20:00:00
1,2,2014,5.0,Minnesota,MN,MRO,East North Central,-0.1,normal,intentional attack,...,2279.0,1700.5,18.2,2.14,0.6,91.592666,8.407334,5.478743,2014-05-11 18:38:00,2014-05-11 18:39:00
2,3,2010,10.0,Minnesota,MN,MRO,East North Central,-1.5,cold,severe weather,...,2279.0,1700.5,18.2,2.14,0.6,91.592666,8.407334,5.478743,2010-10-26 20:00:00,2010-10-28 22:00:00
3,4,2012,6.0,Minnesota,MN,MRO,East North Central,-0.1,normal,severe weather,...,2279.0,1700.5,18.2,2.14,0.6,91.592666,8.407334,5.478743,2012-06-19 04:30:00,2012-06-20 23:00:00
4,5,2015,7.0,Minnesota,MN,MRO,East North Central,1.2,warm,severe weather,...,2279.0,1700.5,18.2,2.14,0.6,91.592666,8.407334,5.478743,2015-07-18 02:00:00,2015-07-19 07:00:00

### univariate analysis

In [9]:
# Plot 1: Distribution of Outage Duration
fig_uni_1 = px.histogram(df_cleaned, x='OUTAGE.DURATION', nbins=50, 
                         title='Distribution of Outage Durations (Minutes)',
                         labels={'OUTAGE.DURATION': 'Outage Duration (Mins)'})
fig_uni_1.write_html("outage_duration.html", include_plotlyjs='cdn')
fig_uni_1.show()

# Plot 2: Distribution of Outage Causes
fig_uni_2 = px.bar(df_cleaned['CAUSE.CATEGORY'].value_counts().reset_index(), 
                   x='CAUSE.CATEGORY', y='count', 
                   title='Count of Outages by Cause Category')
fig_uni_2.write_html("cause_category.html", include_plotlyjs='cdn')
fig_uni_2.show()

### Bivariate analysis

In [10]:
df['START.MONTH'] = df['START.DATETIME'].dt.month_name()

fig_bi_1 = px.box(df, 
                  x='START.MONTH', 
                  y='OUTAGE.DURATION',
                  title='Distribution of Outage Duration by Month',
                  category_orders={"START.MONTH": ["January", "February", "March", "April", "May", "June", 
                                                   "July", "August", "September", "October", "November", "December"]},
                  labels={'START.MONTH': 'Month', 'OUTAGE.DURATION': 'Outage Duration (Minutes)'})

fig_bi_1.update_yaxes(type="log")
fig_bi_1.write_html("duration_month.html", include_plotlyjs='cdn')
fig_bi_1.show()

### intresting aggregates

In [11]:
# Group by Climate Region and Cause, looking at median duration and average customers affected
agg_table = df_cleaned.groupby(['CLIMATE.REGION', 'CAUSE.CATEGORY']).agg({
    'OUTAGE.DURATION': 'median',
    'CUSTOMERS.AFFECTED': 'mean'
}).reset_index().round(2)

# Pivot the table for better readability
pivot_table = agg_table.pivot(index='CLIMATE.REGION', columns='CAUSE.CATEGORY', values='OUTAGE.DURATION')
display(pivot_table)

CAUSE.CATEGORY,equipment failure,fuel supply emergency,intentional attack,islanding,public appeal,severe weather,system operability disruption
CLIMATE.REGION,,,,,,,
Central,149.0,7500.5,50.0,96.0,1410.0,1680.0,65.0
East North Central,761.0,13564.0,648.5,1.0,733.0,4005.0,2694.0
Northeast,159.0,12240.0,1.0,881.0,2760.0,3189.0,234.5
Northwest,702.0,1.0,74.0,21.0,898.0,3507.0,157.5
South,227.0,20160.0,100.0,493.5,430.0,2027.5,373.0
Southeast,308.5,NaN,108.0,NaN,4320.0,1355.0,110.0
Southwest,35.0,76.0,56.0,2.0,2275.0,2425.0,284.0
West,269.0,882.5,108.0,128.5,420.0,962.0,199.0
West North Central,61.0,NaN,0.5,56.0,439.5,83.0,NaN